config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

get 'look/at'

root 'store#index' , as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- START_HIGHLIGHT -->
  <title>Pragprog Books Online Store</title>
<!-- END_HIGHLIGHT -->
  <!-- <label id="code.slt"/> --><%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %><!-- <label id="code.jlt"/> -->
  <%= csrf_meta_tags %><!-- <label id="code.csrf"/> -->
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START_HIGHLIGHT -->
  <div id="banner">
    <%= image_tag("scenery2.jpg", size: '60x30') %>
    <%= @page_title || "Pragmatic Bookshelf" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
    <div id="cart">
      <%= hidden_div_if @cart.line_items.empty?, id: 'cart' do %>
      <%= render @cart%>
      <% end %>
    </div>

      <ul>
        <li><a href="<%= store_url %>">Home</a></li>
        <li><a href="www.xiexinwen.com">Questions</a></li>
        <li><a href="www.baidu.com/news">News</a></li>
        <li><a href="www.github.com/vanishedzhou">Contact</a></li>
      </ul>
    </div>
    <div id="main">
<!-- END_HIGHLIGHT -->
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
<!-- START_HIGHLIGHT -->
    </div>
  </div>
<!-- END_HIGHLIGHT -->
</body>
</html>